=== AUC041222/order-translator/data/logistik/input_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "object",
  "properties": {
    "customerCity": {
      "type": "string"
    },
    "pickingDateFrom": {
      "type": "string",
      "format": "date"
    },
    "customerCountryCode": {
      "type": "string",
      "enum": [
        "DE",
        "CH",
        "AT",
        "BE",
        "NL",
        "LI",
        "LU"
      ],
      "description": "ISO 3166 ALPHA-2 Code des Landes"
    },
    "pickingDateTo": {
      "type": "string",
      "format": "date"
    },
    "deliveryDate": {
      "type": "string",
      "format": "date"
    },
    "customerZipCode": {
      "type": "string",
      "minLength": 4
    },
    "orderNo": {
      "type": "string",
      "minLength": 2
    },
    "customerStreet": {
      "type": "string",
      "minLength": 2
    },
    "customerName": {
      "type": "string",
      "minLength": 2
    },
    "packingCategory": {
      "type": "string",
      "enum": [
        "b2b",
        "b2c"
      ]
    },
    "items": {
      "type": "array",
      "minItems": 1,
      "items": [
        {
          "type": "object",
          "properties": {
            "gtin": {
              "type": "integer"
            },
            "quantity": {
              "type": "integer",
              "minimum": 1
            }
          },
          "required": [
            "gtin",
            "quantity"
          ]
        }
      ]
    },
    "orderDate": {
      "type": "string",
      "format": "date"
    },
    "customerNo": {
      "type": "string",
      "minLength": 3
    }
  },
  "required": [
    "customerCity",
    "pickingDateFrom",
    "customerCountryCode",
    "pickingDateTo",
    "deliveryDate",
    "customerZipCode",
    "orderNo",
    "customerStreet",
    "customerName",
    "packingCategory",
    "items",
    "customerNo"
  ]
}

=== AUC041222/order-translator/data/input_logistik.json
{
    "customerCity": "Ansbach",
    "pickingDateFrom": "2022-07-22",
    "customerCountryCode": "DE",
    "pickingDateTo": "2022-07-22",
    "deliveryDate": "2022-07-23",
    "customerZipCode": "91522",
    "orderNo": "96220979207493",
    "customerStreet": "Bahnhofsplatz 8\nc/o Zalando SE",
    "customerName": "Mia Musterer",
    "packingCategory": "b2b",
    "items": [
        {
            "gtin": 4059117317163,
            "quantity": 3
        },
        {
            "gtin": 4059117317180,
            "quantity": 2
        }
    ],
    "orderDate": "2022-07-22",
    "customerNo": "9170426526"
}
